---
resources:
- name: service-backup-release
  type: git
  source:
    branch: develop
    private_key: {{service-backup-release-private-key}}
    uri: git@github.com:pivotal-cf-experimental/service-backup-release

- name: service-backup-ci-image
  type: docker-image
  source:
    username: {{docker-username}}
    email: {{docker-email}}
    password: {{docker-password}}
    repository: cflondonservices/service-backup

jobs:
- name: integration-test
  plan:
  - get: service-backup-release
    trigger: true
  - task: integration-test
    file: service-backup-release/scripts/ci/test_integration.yml
    config:
      params:
        AWS_ACCESS_KEY_ID: {{integration-test-aws-access-key-id}}
        AWS_SECRET_ACCESS_KEY: {{integration-test-aws-secret-access-key}}

- name: docker-image
  plan:
  - get: service-backup-release
    trigger: true
  - put: service-backup-ci-image
    params: {build: service-backup-release/scripts/ci/}
