#!/bin/bash

set -eux

MY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# This script expects to live two directories below the base directory.
BASE_DIR="$( cd "${MY_DIR}/../.." && pwd )"

AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:?}"
AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:?}"

export GOPATH=${BASE_DIR}
export GOROOT=${GOPATH}
export PATH=${GOPATH}/bin:${PATH}

pushd "${BASE_DIR}"
  go install github.com/onsi/ginkgo/ginkgo
  ./src/github.com/pivotal-cf-experimental/service-backup/scripts/ci/test_integration
popd
