#!/bin/bash

set -e

pushd $(dirname $0)/..

# ensure gosub is installed (this will recompile it only if necessary)
go get github.com/vito/gosub
go install github.com/vito/gosub

function sync_package() {
  bosh_pkg=${1}
  shift

  (
    set -e

    cd packages/${bosh_pkg}

    {
      grep -v '# gosub' spec

      for package in $(gosub list "$@"); do
        repo=$(echo ${2} | cut -f1-3 -d/)
        if [ -d "../../src/${repo}/Godeps/_workspace/src/${package}" ]; then
          package="${repo}/Godeps/_workspace/src/${package}"
        fi
        echo ${package} | sed -e 's/\(.*\)/  - \1\/*.go # gosub/g'
      done
    } > spec.new

    mv spec.new spec
  )
}

sync_package service-backup \
  -app github.com/pivotal-cf-experimental/service-backup \
  -app github.com/pivotal-cf-experimental/service-backup/cmd/manual-backup

popd
