---
resources:
- name: service-backup-release
  type: git
  source:
    branch: develop
    private_key: {{git-private-key}}
    uri: git@github.com:pivotal-cf-experimental/service-backup-release

jobs:
- name: integration-test
  plan:
  - get: service-backup-release
    trigger: true
  - task: integration-test
    file: service-backup-release/ci/test_integration.yml
    privileged: true
    config:
      params:
        AWS_ACCESS_KEY_ID: {{service-backup-test-bucket-access-key}}
        AWS_SECRET_ACCESS_KEY: {{service-backup-test-bucket-secret-key}}
